### ISSUE TITLE
SNS configuration

### ISSUE THREAD

**Issue by alikarami010** [dasniko/keycloak-2fa-sms-authenticator#12]
Hi @dasniko ,
Thank you to share this useful code with us. We engaged in your 2FA Authentication SMS project and we did successfully simulate sending the verification code in SIMULATION_MODE as you described in your code.
Unfortunately we stuck on configuring Keycloak to send real verification code through aws SNS.
We believe we configure the SNS correctly, and activate our Origination numbers and verified our receivers mobile phone through SNS dashboard.
Maybe there is some minor configuration steps that are remaining in our Keycloak side that we are not aware of it. What we did in your code and create the .jar file are as follows:
1- Use your keycloak-2fa-sms-authenticator sample code and change the following:
System.setProperty (“aws.accessKeyId”, MYACCESSKEYID);
System.setProperty (“aws.secretAccessKey”, MYSECRETACCESSKEY);
System.setProperty (“aws.region”, “ca-central-1");
That’s the only change that we did up to now. We need you help to guide us if any other configuration remaining. Thank you in advance for you support.
It is my error after run :
ERROR [org.keycloak.services.error.KeycloakErrorHandler] (default task-2) Uncaught server error: java.lang.NoClassDefFoundError: org/reactivestreams/Publisher

**Comment by dasniko** [comment]
Thanks for this, there was a config missing in the shade plugin configuration. Should work now.

**Comment by alikarami010** [comment]
thanks for changes but i have new error
ERROR [org.keycloak.services.error.KeycloakErrorHandler] (default task-2) Uncaught server error: java.lang.NoClassDefFoundError: org/keycloak/common/util/SecretGenerator

**Comment by dasniko** [comment]
The code is valid vor Keycloak v17+, see pom.xml

**Comment by alikarami010** [comment]
My version is keycloak-15.0.2

**Comment by dasniko** [comment]
Well, then you'll have to refactor something. Either your environment or the code.
This is an example repository, there's no support available for it!

**Comment by alikarami010** [comment]
Thaanks so much , I can upgrade Keycloak to version 17
