### ISSUE TITLE
SMS Provider

### ISSUE THREAD

**Issue by AlexeiKlimenko** [dasniko/keycloak-2fa-sms-authenticator#15]
Keycloak - Version 17.0.0
When selecting Provider in execution task "SMS Authentication" is absent in the list.

Does that mean that your project is not applicable with newest versions of keycloak?

**Comment by dasniko** [comment]
It works without problems with 17.x
Seems, that you did something wrong in your deployment.

**Comment by AlexeiKlimenko** [comment]
You've written about "deployed the JAR profile to the the /deployments directory" but keycloak doesn't have any folder like it:

drwxr-xr-x  8 root root  4096 Apr 19 09:20 .
drwxr-xr-x 12 root root  4096 Apr 21 13:54 ..
-rw-r--r--  1 root root 11358 Apr  5 15:58 LICENSE.txt
-rw-r--r--  1 root root   492 Apr  5 15:58 README.md
drwxr-xr-x  3 root root  4096 Apr  5 15:58 bin
-rw-r--r--  1 root root  2199 Apr 19 09:20 cacerts
drwxr-xr-x  2 root root  4096 Apr  6 11:24 conf
drwxr-xr-x  4 root root  4096 Apr  5 16:01 data
-rw-r--r--  1 root root  2199 Apr 18 16:59 keycloak.jks
drwxr-xr-x  5 root root  4096 Apr  5 15:58 lib
drwxr-xr-x  2 root root  4096 Apr  5 15:58 providers
drwxr-xr-x  2 root root  4096 Apr  5 15:58 themes
-rw-r--r--  1 root root    26 Apr  5 15:58 version.txt

Unfortunately, we haven't found any suitable info about implementation.

**Comment by dasniko** [comment]
Seems like it's a legacy information as the legacy (Wildfly) Keycloak had the `/deployments` folder. Now (Quarkus) it's `/providers`.

Please note that this is an example repository. There are no guaranties nor warranties in any means!

**Comment by AlexeiKlimenko** [comment]
So, we have created JAR file with source and pom.xml and put it into /providers. 
During building we've got:
Exception in thread "main" java.io.EOFException
	at java.base/java.io.DataInputStream.readBoolean(DataInputStream.java:249)
	at io.quarkus.bootstrap.runner.SerializedApplication.read(SerializedApplication.java:119)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:53)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:31)
